### ISSUE TITLE
Setting up CI of this website on libbitcoin.dyne.org

### ISSUE THREAD

**Issue by jaromil** [libbitcoin/libbitcoin.github.io#2]
Will automate with a cronjob

**Comment by ghost** [comment]
@jaromil ok - cool :)

**Comment by ABISprotocol** [comment]
Team page for libbitcoin.dyne.org says (current contributors)

 Amir Taaki
Noel Maersk
Thomas Hartmann
Eric Voskuil
William Swanson
Grazcoin 

However, there's just one person showing in the github organization under 
https://github.com/libbitcoin

Curious if the wiki and github need updating?

**Comment by evoskuil** [comment]
I see 12 people listed in the libbitcoin organization: https://github.com/orgs/libbitcoin/people

**Comment by thecodefactory** [comment]
The organization list is private, only viewable by members.

**Comment by thecodefactory** [comment]
Ah, actually each person would have to specify that they want to be visible in that list.  I just made mine public and it worked (for non-logged in accounts).

**Comment by ABISprotocol** [comment]
ok, tyvm

**Comment by jaromil** [comment]
heads up guys
totally my fault if the website update plan is still not in place . gonna do it now.
BTW I suppose this project will become enormously important after bitcoin core 0.12 release...

**Comment by ABISprotocol** [comment]
it looks like I missed this somehow, how old is this thing?  Not sure if
I already specified, but I'm ok being visible in the list of people
associated with libbitcoin project / contribution, though my
contributions have been tiny.

thecodefactory:
> Ah, actually each person would have to specify that they want to be visible in that list.  I just made mine public and it worked (for non-logged in accounts).
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/libbitcoin/libbitcoin.github.io/issues/2#issuecomment-174215918
> 

-- 
http://abis.io ~
"a protocol concept to enable decentralization
and expansion of a giving economy, and a new social good"
https://keybase.io/odinn

**Comment by evoskuil** [comment]
Visibility is configured by the individual.

**Comment by jaromil** [comment]
hi Eric. I have setup a webhook for updates of libbitcoin.dyne.org via this git repository. Details in private.
