### ISSUE TITLE
C and Swift Binding for libbitcoin for iOS Cocoapods

### ISSUE THREAD

**Issue by ChristopherA** [libbitcoin/libbitcoin.github.io#7]
At @BlockchainCommons we are developing iOS wallet apps (a BTC airgap wallet and BTCR Decentralized Identity (DID) Wallet  (see [spec](https://w3c-ccg.github.io/didm-btcr/) & [implementation notes](https://github.com/WebOfTrustInfo/rwot7-toronto/blob/master/final-documents/btcr_0_1.md))) using libbitcoin, led by long-time iOS developer @wolfmcnally. 

https://github.com/BlockchainCommons/iOS-Bitcoin iOS-Bitcoin — Swift 4.2 bindings for libbitcoin. This Bitcoin framework depends on the CBitcoin framework, which includes a pre-made build of libbitcoin. To properly install this, you need to first install the latest version of Git and the Git Large File Storage handler.

https://github.com/BlockchainCommons/iOS-CBitcoin iOS-CBitcoin - C bindings for libbitcoin. Intended primarily as support for the Bitcoin framework, which depends on this one and provides Swift bindings for libbitcoin. 

Both of these are designed to support use with iOS Cocoapods.

You are welcome to list them on your website if appropriate.

**Comment by wolfmcnally** [comment]
I am the author of these frameworks and I have just written a blog post announcing their availability here: https://wolfmcnally.com/125/announcing-open-source-bitcoin-framework-for-ios/

**Comment by thecodefactory** [comment]
@ChristopherA Cool!  The mailing list is probably a better place for this kind of announcement.  The 'official' libbitcoin website update process is not something I know much about personally.

@wolfmcnally Excellent, thanks!
